version: "3.8"

services:
  rust_api_db:
    container_name: rust_api_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=happy
      - POSTGRES_PASSWORD=happy
      - POSTGRES_DB=happy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}

